### ISSUE TITLE
ultrasound.so: undefined symbol

### ISSUE THREAD

**Issue by davidbradway** [davidbradway/TFprocessing#1]
I ran `python bf_local.py --worker_hosts=localhost:2500 --job_name=worker --task_index=0` 
but got the error below:
```bash
Traceback (most recent call last):
  File "bf_local.py", line 93, in <module>
    exec tparser.return_code()
  File "<string>", line 33, in <module>
  File "/getlab/dpb6/repos/TFprocessing/src/core/ultrasound_tensor_ops.py", line 51, in __init__
    self._ultrasound_op = load_library.load_op_library(os.path.join(os.path.dirname(os.path.realpath(__file__)),'ultrasound.so'))
  File "/scratch/dpb6/anaconda3/envs/py2tf1/lib/python2.7/site-packages/tensorflow/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /getlab/dpb6/repos/TFprocessing/src/core/ultrasound.so: undefined symbol: _ZTIN10tensorflow8OpKernelE
```

**Comment by davidbradway** [comment]
Made a new conda environment that was Tensorflow 1.1 as Carlos said he used, rather than the 1.13 I had.
This then resulted in a different error: `tensorflow.python.framework.errors_impl.NotFoundError: undefined symbol: _ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringB5cxx11Ev`, which I googled: https://github.com/tensorflow/tensorflow/issues/1569 It suggested to compile with flag `-D_GLIBCXX_USE_CXX11_ABI=0`

**Comment by davidbradway** [comment]
Solved the above error. 
The correct compile statement is: `g++ -v -std=c++11 -mavx -fopenmp -O2 -shared ultrasound.cc -o ultrasound.so -I /scratch/dpb6/anaconda3/envs/tf11/lib/python2.7/site-packages/tensorflow/include -fPIC -D_GLIBCXX_USE_CXX11_ABI=0 -lfftw3 -lm` to be able to use my newer GCC version. 

The new error I am tracking down is: `IOError: [Errno 2] No such file or directory: 'element_data/flow/seq_0001/elem_data_em0001.mat'`

**Comment by davidbradway** [comment]
Dealt with a path problem in how the paths were set to look at the `data` directory, which is not included in this repo. After this change it starts to run, but crashes when it looks for the second frame of data.

**Comment by davidbradway** [comment]
I changed the indexing in the `bf_local.xml` file to reflect the smaller dataset that was provided (not in repo). After this change it does run, but appears to lock up my computer and not produce output.
